- name: Creates secrets required for docker registry Authentication
  hosts: control_plane
  vars:
    docker_server: docker-registry.cluster.local
  tasks:
    - name: Load docker registry user name from file
      ansible.builtin.command:
        cmd: cat /shared_storage/share/user
      register: user_name
      changed_when: false

    - name: Load docker registry password from file
      ansible.builtin.command:
        cmd: cat /shared_storage/share/password
      register: user_password
      changed_when: false

    - name: Load docker-credentials-json from file
      ansible.builtin.command:
        cmd: cat /shared_storage/share/docker-credentials-json
      register: docker_credentials_json
      changed_when: false

    - name: Load htpasswd from file
      ansible.builtin.command:
        cmd: cat /shared_storage/share/htpasswd
      register: htpasswd_output
      changed_when: false

    - name: Create docker-registry namespace
      kubernetes.core.k8s:
        state: present
        src: /shared_storage/manifests/docker-registry/docker-registry-ns.yaml

    - name: Create secret with docker credentials used in manifests (pod authentication approach)
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: docker-registry-credentials
            namespace: docker-registry-ns
          type: kubernetes.io/dockerconfigjson
          data:
            .dockerconfigjson: "{{ docker_credentials_json | to_json | b64encode }}"

    - name: Create secret with htpasswd file
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: registry-auth
            namespace: docker-registry-ns
          type: Opaque
          data:
            htpasswd: "{{ htpasswd_output.stdout | b64encode }}"
