- name: Creates routing objects and dependant objects
  hosts: control_plane
  tasks:
    - name: Create CA certificate
      kubernetes.core.k8s:
        state: present
        src: /shared_storage/manifests/registry-routing/ca-certificate.yaml

    - name: Create registry certificate
      kubernetes.core.k8s:
        state: present
        src: /shared_storage/manifests/registry-routing/registry-certificate.yaml
