- name: Adds authentication with httpasswd
  hosts: control_plane
  gather_facts: true
  vars:
    user: docker-user
    password: docker-password
  tasks:
    - name: Ensure that apache2-utils are installed
      become: true
      ansible.builtin.apt:
        name: apache2-utils
        state: present

    - name: Generate password file contents
      become: true
      community.docker.docker_container:
        name: htpasswd_generator
        image: httpd:2
        command: ["htpasswd", "-Bbn", "{{ user }}", "{{ password }}"]
        detach: false
        cleanup: true
        state: present
      register: htpasswd_output


    - name: Save password file contents to file
      become: true
      ansible.builtin.copy:
        content: "{{ htpasswd_output.stdout }}"
        dest: "/shared_storage/share/htpasswd"
        mode: "0644"

    - name: Create secret with htpasswd file
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: registry-auth
            namespace: docker-registry-ns
          type: Opaque
          data:
            auth: "{{ lookup('file', '/shared_storage/share/htpasswd') }}"
