- name: Adds authentication with httpasswd
  hosts: control_plane
  gather_facts: true
  vars:
    user: docker-user
    password: docker-password
  tasks:
    - name: Ensure that apache2-utils are installed
      become: true
      ansible.builtin.apt:
        name: apache2-utils
        state: present

    - name: Generate password file contents
      become: true
      ansible.builtin.shell: |
        htpasswd -Bbn {{ user }} {{ password }}
      register: htpasswd_output
      changed_when: false

    - name: Print htpasswd content
      ansible.builtin.debug:
        msg: "{{ htpasswd_output.stdout }}"

    - name: Save password file contents to file
      become: true
      ansible.builtin.copy:
        content: "{{ htpasswd_output.stdout }}"
        dest: "/shared_storage/share/htpasswd"
        mode: "0644"

    - name: Create secret with htpasswd file
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: registry-auth
            namespace: docker-registry-ns
          type: Opaque
          data:
            auth: "{{ htpasswd_output.stdout | b64encode}}"
