- name: Creates ingress rule for docker registry
  hosts: control_plane
  tasks:
    - name: Wait for Nginx Ingress Controller to be ready
      kubernetes.core.k8s_info:
        kind: Deployment
        name: ingress-nginx-controller
        namespace: ingress-nginx
        wait: true
        wait_sleep: 6
        wait_timeout: 60

    - name: Create ingress rule for registry
      kubernetes.core.k8s:
        state: present
        src: /shared_storage/manifests/registry-routing/routing-ingress.yaml
