- name: Creates ingress rule for docker registry
  hosts: control_plane
  tasks:
    - name: Create ingress rule for registry
      kubernetes.core.k8s:
        state: present
        src: /shared_storage/manifests/registry-routing/routing-ingress.yaml
