- name: Creates ingress rule for docker registry
  hosts: control_plane
  tasks:
    - name: Create ingress rule for registry
      ansible.builtin.command:
        cmd: kubectl apply -f /shared_storage/manifests/registry-routing/routing-ingress.yaml
