- name: Retrieves certificate and moves it to shared directory
  hosts: control_plane
  tasks:
    - name: Retrieve CA certificate
      kubernetes.core.k8s_info:
        kind: Secret
        name: mat-grz-ca-secret
        namespace: docker-registry-ns
      register: encoded_cert

    - name: Decode cert and save it to file
      ansible.builtin.copy:
        content: "{{ encoded_cert.resources[0].data['ca.crt'] | b64decode }}"
        dest: /shared_storage/share/ca.crt
        mode: '0644'
