- name: Configures nodes to be able to use TLS communication
  hosts: kubernetes_common
  tasks:
    - name: Wait till ingress-controller obtains external IP from metallb
      ansible.builtin.command:
        cmd: >
          kubectl get service/ingress-nginx-controller
          -n ingress-nginx
          -o jsonpath='{.status.loadBalancer.ingress[0].ip}'
      register: check_external_ip
      until: check_external_ip.stdout != ""
      retries: 10
      delay: 6
      changed_when: false

    - name: Retrieve ingress-controller external IP
      ansible.builtin.command:
        cmd: >
          kubectl get service/ingress-nginx-controller
          -n ingress-nginx
          -o jsonpath='{.status.loadBalancer.ingress[0].ip}'
      register: external_ip
      changed_when: false
      failed_when: external_ip.stdout == ""

    - name: Create host entry for ingress-controller
      become: true
      ansible.builtin.command:
        cmd: >
          echo "{{ external_ip.stdout }} docker-registry.cluster.local" >> /etc/hosts

    - name: Copy CA certificate
      become: true
      ansible.builtin.command:
        cmd: cp /shared_storage/share/ca.crt /usr/local/share/ca-certificates/ca.crt

    - name: Reload ca-certificates
      become: true
      ansible.builtin.command:
        cmd: update-ca-certificates
