# Ensure that playbook for installing Helm package manager was ran beforehand
- name: Adds cert-manager to cluster
  hosts: control_plane
  tasks:
    - name: Adds Helm repository
      kubernetes.core.helm_repository:
        repo_name: jetstack
        repo_url: https://charts.jetstack.io
        force_update: true

    - name: Install cert-manager Helm chart
      kubernetes.core.helm:
        chart_ref: jetstack/cert-manager
        name: cert-manager
        release_namespace: cert-manager
        create_namespace: true
        chart_version: 'v1.16.2'
        values:
          installCRDs: true
