- name: Install KNative Kourier for networking layer
  hosts: control_plane
  tasks:
    - name: Install KNative Kourier controller
      kubernetes.core.k8s:
        src: /shared_storage/drivers_CRD/knative/networking/kourier.yaml
        state: present

    - name: Configure Knative Serving to use Kourier by default
      kubernetes.core.k8s:
        namespace: knative-eventing
        kind: ConfigMap
        name: config-network
        definition:
          data:
            ingress-class: kourier.ingress.networking.knative.dev
        state: patched
