- name: Adds MetalLB to the cluster.
  hosts: control_plane
  tasks:
    - name: Get Helm repository
      ansible.builtin.command:
        cmd: helm repo add metallb https://metallb.github.io/metallb

    - name: Update helm repositories
      ansible.builtin.command:
        cmd: helm repo update

    - name: Create namespace for Metallb
      ansible.builtin.command:
        cmd: kubectl create namespace metallb-system

    - name: Install MetalLB
      ansible.builtin.command:
        cmd: helm install metallb metallb/metallb --namespace metallb-system
