# Ensure that playbook for installing Helm package manager was ran beforehand
- name: Adds cert-manager to cluster
  hosts: control_plane
  tasks:
    - name: Adds Helm repository
      ansible.builtin.shell: |
        helm repo add jetstack https://charts.jetstack.io --force-update

    - name: Install cert-manager Helm chart
      ansible.builtin.shell: |
        helm install \
          cert-manager jetstack/cert-manager \
          --namespace cert-manager \
          --create-namespace \
          --version v1.16.2 \
          --set crds.enabled=true
