- name: Set up Control Plane
  hosts: control_plane
  become: true
  gather_facts: true
  tasks:
    - name: Print pod network cidr
      ansible.builtin.debug:
        var: pod_network_cidr

    - name: Check if kubeinit has been called
      ansible.builtin.stat:
        path: /etc/kubernetes/kubelet.conf
      register: kubeinit_called

    - name: Initialize the Kubernetes cluster using kubeadm
      ansible.builtin.command:
        cmd: >
          kubeadm init
          --apiserver-advertise-address="{{ node_ip }}"
          --apiserver-cert-extra-sans="{{ node_ip }}"
          --node-name {{ ansible_hostname }}
          --pod-network-cidr="{{ pod_network_cidr }}"
      when: not kubeinit_called.stat.exists
      changed_when: false

    - name: Setup kubeconfig for user
      ansible.builtin.command: "{{ item }}"
      with_items:
        - mkdir -p /home/{{ ansible_user }}/.kube
        - cp -i /etc/kubernetes/admin.conf /home/{{ ansible_user }}/.kube/config
        - chown {{ ansible_user }}:{{ ansible_user }} /home/{{ ansible_user }}/.kube/config
      when: not kubeinit_called.stat.exists
      changed_when: false

    - name: Copy the flannel manifest to the CP node
      ansible.builtin.copy:
        src: ./k8s/kube-flannel.yml
        dest: /tmp/kube-flannel.yml
        mode: '0777'

    - name: Apply Flannel CNI manifest
      become: false
      ansible.builtin.command:
        cmd: kubectl apply -f /tmp/kube-flannel.yml
      changed_when: false

    - name: Generate join command
      ansible.builtin.command:
        cmd: kubeadm token create --print-join-command
      register: join_command
      changed_when: false

    - name: Copy join command to local file
      become: false
      ansible.builtin.copy:
        content: "{{ join_command.stdout_lines[0] }}"
        dest: "./tmp/join-command"
        mode: '0755'
      delegate_to: localhost
