- name: Create KRaft kafka cluster
  hosts: control_plane
  tasks:
    - name: Create kafka cluster
      kubernetes.core.k8s:
        src: /shared_storage/manifests/kafka-cluster/kafka-cluster.yaml
        state: present
