- name: Install Strimzi with CRDs and RBAC configuration
  hosts: control_plane
  vars:
    operator_ns: kafka-operator-ns
    deployment_ns: kafka-cluster-ns
    source_files_path: /shared_storage/drivers_CRD/strimzi
  tasks:
    - name: Create namespace "kafka-operator-ns" for cluster operator
      kubernetes.core.k8s:
        api_version: v1
        name: "{{ operator_ns }}"
        kind: Namespace
        state: present

    - name: Create namespace "kafka-cluster-ns" for kafka cluster deployment
      kubernetes.core.k8s:
        api_version: v1
        name: "{{ deployment_ns }}"
        kind: Namespace
        state: present

    - name: Get installation files for modifying
      become: true
      ansible.builtin.find:
        paths: "{{ source_files_path }}/install/cluster-operator"
        patterns: "*RoleBinding*.yaml"
        recurse: false
      register: installation_files

    - name: Modify installation files to reference cluster operator namespace
      become: true
      ansible.builtin.replace:
        path: "{{ item.path }}"
        regexp: 'namespace: .*'
        replace: "namespace: {{ operator_ns }}"
      loop: "{{ installation_files.files }}"

    - name: Modify STRIMZI_NAMESPACE env in 060-Deployment-strimzi-cluster-operator.yaml
      become: true
      ansible.builtin.shell:
        cmd: "sed -i '/- name: STRIMZI_NAMESPACE/{n; s/value:.*/value: {{ operator_ns }},{{ deployment_ns }}/}' {{ source_files_path }}/install/cluster-operator/060-Deployment-strimzi-cluster-operator.yaml"

    - name: Add permissions for cluster operator to watch cluster operator namespace
      kubernetes.core.k8s:
        state: present
        src: "{{ source_files_path }}/install/cluster-operator/020-RoleBinding-strimzi-cluster-operator.yaml"
        namespace: "{{ operator_ns }}"

    - name: Add permissions for cluster operator
      kubernetes.core.k8s:
        state: present
        src: "{{ source_files_path }}/install/cluster-operator/023-RoleBinding-strimzi-cluster-operator.yaml"
        namespace: "{{ operator_ns }}"

    - name: Add permissions for cluster operator to watch cluster operator namespace
      kubernetes.core.k8s:
        state: present
        src: "{{ source_files_path }}/install/cluster-operator/031-RoleBinding-strimzi-cluster-operator-entity-operator-delegation.yaml"
        namespace: "{{ operator_ns }}"

    - name: Add permissions for cluster operator to watch cluster deployment namespace
      kubernetes.core.k8s:
        state: present
        src: "{{ source_files_path }}/install/cluster-operator/020-RoleBinding-strimzi-cluster-operator.yaml"
        namespace: "{{ deployment_ns }}"

    - name: Add permissions for cluster operator
      kubernetes.core.k8s:
        state: present
        src: "{{ source_files_path }}/install/cluster-operator/023-RoleBinding-strimzi-cluster-operator.yaml"
        namespace: "{{ deployment_ns }}"

    - name: Add permissions for cluster operator to watch cluster deployment namespace
      kubernetes.core.k8s:
        state: present
        src: "{{ source_files_path }}/install/cluster-operator/031-RoleBinding-strimzi-cluster-operator-entity-operator-delegation.yaml"
        namespace: "{{ deployment_ns }}"

    - name: Get all manifest files from cluster-operator directory
      ansible.builtin.find:
        paths: "{{ source_files_path }}/install/cluster-operator/"
        patterns: "*.yaml"
        recurse: false
      register: manifest_files

    - name: Deploy CRDs and RBAC resources to manage CRDs
      kubernetes.core.k8s:
        state: present
        src: "{{ item.path }}"
        namespace: "{{ operator_ns }}"
      loop: "{{ manifest_files.files }}"
